org-timeblock-clock-in and org-timeblock-clock-out
ichernyshovvv/org-timeblock pull request #20
Opened 2023-08-26 18:12 UTC by balaramadurai

clocking entries from the timeblocks can be possible with these functions, mapped to "i" and "o"

2023-08-29 00:03 UTC, alphapapa requested changes
I took the liberty of doing a quick review on this useful-looking PR.  :)

2023-08-29 00:03 UTC, alphapapa commented on org-timeblock.el
> +	             (m (cadr (seq-find (lambda (x) (string= (car x) id)) ot-data))))
This indentation is off.

2023-08-29 00:03 UTC, alphapapa commented on org-timeblock.el
> +	             (m (cadr (seq-find (lambda (x) (string= (car x) id)) ot-data))))
Single-letter variable names should generally be avoided.  Descriptive ones make code easier to read.  :)

Also, consider using a form like, `(cl-find id ot-data :key #'car :test #'equal)`.

2023-08-29 00:03 UTC, alphapapa commented on org-timeblock.el
> +      (switch-to-buffer-other-window (marker-buffer m))
You'll likely want to use `save-window-excursion`, unless you want the user to actually switch away from the timeblock view.

2023-09-16 12:32 UTC, ichernyshovvv commented
Hi, implemented in https://github.com/ichernyshovvv/org-timeblock/commit/d83fe8edbda7ebecf42cad310bac9e8412f9a9db. Please check if it works for you.

2023-09-17 13:13 UTC, closed without merging

2023-09-18 06:40 UTC, balaramadurai commented
Yes, this works! Thanks @ichernyshovvv for your help. 

I spend more time on timeblock than org-agenda now. :smile: